######################################################################
# Automatically generated by qmake (3.0) l�r. nov. 1 21:22:18 2014
######################################################################

TEMPLATE = app
TARGET = src
INCLUDEPATH += .

CONFIG += c++11

QT += network widgets
# Input
HEADERS += aes.h \
           constants.h \
           crypto.h \
           snapchat.h \
           friendsmodel.h \
           snapmodel.h \
    testwidget.h
SOURCES += aes.c \
           crypto.cpp \
           main.cpp \
           snapchat.cpp \
           friendsmodel.cpp \
           snapmodel.cpp \
    testwidget.cpp
